_BASE_: "Base-CenterMask-Lite-VoVNet_blob.yaml"
MODEL:
  WEIGHTS: "datasets/vovnet39_ese_detectron2.pth"
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (10000, 20000, 30000, 40000, 50000)
  MAX_ITER: 60000
TEST:
  DETECTIONS_PER_IMAGE: 1000